/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_decoder_xiaomi_H265Decoder */

#ifndef _Included_com_decoder_xiaomi_H265Decoder
#define _Included_com_decoder_xiaomi_H265Decoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_decoder_xiaomi_H265Decoder
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_decoder_xiaomi_H265Decoder_nativeInit
        (JNIEnv *, jclass);

/*
 * Class:     com_decoder_xiaomi_H265Decoder
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_decoder_xiaomi_H265Decoder_init
        (JNIEnv *, jobject);

/*
 * Class:     com_decoder_xiaomi_H265Decoder
 * Method:    release
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_decoder_xiaomi_H265Decoder_release
        (JNIEnv *, jobject);

/*
 * Class:     com_decoder_xiaomi_H265Decoder
 * Method:    decode
 * Signature: ([BIJ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_decoder_xiaomi_H265Decoder_decode
        (JNIEnv *, jobject, jbyteArray, jint, jlong);

/*
 * Class:     com_decoder_xiaomi_H265Decoder
 * Method:    encode
 * Signature: ([BIJ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_decoder_xiaomi_H265Decoder_encode
        (JNIEnv *, jobject, jbyteArray, jint, jlong);

/*
 * Class:     com_decoder_xiaomi_H265Decoder
 * Method:    decodeBuffer
 * Signature: (Ljava/nio/ByteBuffer;IJ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_decoder_xiaomi_H265Decoder_decodeBuffer
        (JNIEnv *, jobject, jobject, jint, jlong);

/*
 * Class:     com_decoder_xiaomi_H265Decoder
 * Method:    getWidth
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_decoder_xiaomi_H265Decoder_getWidth
        (JNIEnv *, jobject);

/*
 * Class:     com_decoder_xiaomi_H265Decoder
 * Method:    getHeight
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_decoder_xiaomi_H265Decoder_getHeight
        (JNIEnv *, jobject);

/*
 * Class:     com_decoder_xiaomi_H265Decoder
 * Method:    toTexture
 * Signature: (III)I
 */
JNIEXPORT jint JNICALL Java_com_decoder_xiaomi_H265Decoder_toTexture
        (JNIEnv *, jobject, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
